// Code generated by goctl. DO NOT EDIT.
// Source: message.proto

package server

import (
	"context"

	"douyin-message/internal/logic"
	"douyin-message/internal/svc"
	"douyin-message/types"
)

type MessageServer struct {
	svcCtx *svc.ServiceContext
	__.UnimplementedMessageServer
}

func NewMessageServer(svcCtx *svc.ServiceContext) *MessageServer {
	return &MessageServer{
		svcCtx: svcCtx,
	}
}

func (s *MessageServer) Chat(ctx context.Context, in *__.ChatRequest) (*__.ChatResponse, error) {
	l := logic.NewChatLogic(ctx, s.svcCtx)
	return l.Chat(in)
}

func (s *MessageServer) Action(ctx context.Context, in *__.ActionRequest) (*__.ActionResponse, error) {
	l := logic.NewActionLogic(ctx, s.svcCtx)
	return l.Action(in)
}
